#-------------------------------------------------------------------------------
# SPDX-FileCopyrightText: Copyright The TrustedFirmware-M Contributors
#
# SPDX-License-Identifier: BSD-3-Clause
#
#-------------------------------------------------------------------------------

common: !include dma_common.yaml

locations:
    rom:
        base_address: 0x1101F000
        size: 0x1000
    vm0:
        base_address: 0x31000000
        size: 0x10000
        reserved: 0x8
    otp:
        # This has to be manually calculated, and must be updated if the OTP
        # layout changes
        base_address: 0x500A4C00
        size: 0x108
        reserved: 0x8
    integrity_checker:
        base_address: 0x5015C000
    sam:
        base_address: 0x5009F000
    dma350:
        base_address: 0x50002000
    dma_channel_0:
        base_address: 0x50003000
    dma_channel_1:
        base_address: 0x50003100
    dma_channel_2:
        base_address: 0x50003200
    dma_channel_3:
        base_address: 0x50003300
    dtcm:
        base_address: 0x34000000
    lcm:
        base_address: 0x500A0000
    rse_system_control_registers:
        base_address: 0x58021000
    trng:
        base_address: 0x500A5270
    tram:
        base_address: 0x5015D000
    kmu:
        base_address: 0x5009E000

triggers:
     diagnostic_mode: 0
     mission_mode: 1
     mission_provisioning: 2
     secure_enable: 3
     sam_integrity_checker: 4
     integrity_checker: 5

program:
  - storage_location: "rom"
    execution_location: "rom"
    channel: 0
    name: "program0"
    description: "Set up DMA Channel 1"
    commands:
      - !include include/program0_cmd0.yaml         # Program 0 - Command 0
      - !include include/program0_cmd1.yaml         # Program 0 - Command 1
      - !include include/program0_cmd2.yaml         # Program 0 - Command 2

  - storage_location: "rom"
    execution_location: "rom"
    channel: 1
    name: "program1"
    description: "Run only in Virgin TCI mode"
    commands:
      - !include include/program1_cmd0.yaml         # Program 1 - Command 0
      - !include include/program1_cmd1.yaml         # Program 1 - Command 1

  - storage_location: "rom"
    execution_location: "rom"
    channel: 0
    name: "program2"
    description: "P3 P4 Init"
    commands:
      - !include include/program2_cmd0.yaml         # Program 2 - Command 0
      - !include include/program2_cmd1.yaml         # Program 2 - Command 1
      - !include include/program2_cmd2.yaml         # Program 2 - Command 2
      - !include include/program2_cmd3.yaml         # Program 2 - Command 3

  - storage_location: "rom"
    execution_location: "rom"
    channel: 1
    name: "program3"
    description: "Run only in CM and DM modes"
    commands:
      - !include include/program3_cmd0.yaml         # Program 3 - Command 0
      - !include include/program3_cmd1.yaml         # Program 3 - Command 1
      - !include include/program3_cmd2.yaml         # Program 3 - Command 2

  - storage_location: "rom"
    execution_location: "rom"
    channel: 0
    name: "program4"
    description: "OTP ICS loader"
    commands:
      - !include include/program4_cmd0.yaml         # Program 4 - Command 0
      - !include include/program4_cmd1.yaml         # Program 4 - Command 1
      - !include include/program4_cmd2.yaml         # Program 4 - Command 2
      - !include include/program4_cmd3.yaml         # Program 4 - Command 3
      - !include include/program4_cmd4.yaml         # Program 4 - Command 4

  - storage_location: "otp"
    execution_location: "vm0"
    channel: 0
    name: "program5"
    description: "Copy SAM configuration"
    commands:
      - !include include/program5_cmd0.yaml         # Program 5 - Command 0
      - !include include/program5_cmd1.yaml         # Program 5 - Command 1
      - !include include/program5_cmd2.yaml         # Program 5 - Command 2

  - storage_location: "rom"
    execution_location: "rom"
    name: "program6"
    description: "Release DCU lock and CPUWAIT"
    commands:
      - !include include/program6_cmd0.yaml         # Program 6 - Command 0
      - !include include/program6_cmd1.yaml         # Program 6 - Command 1
